apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  config.yml: |
    http:
      port: 8080
      mode: release
    log:
      app:
        path: logs/app.log
        level: DEBUG
      http:
        access-log: logs/access.log
        error-log: logs/error.log
