apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: harbor.local.com/demo/myapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/myapp
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: myapp
  selector:
    matchLabels:
      app: myapp
